//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Transcript_Repository.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Module
    {
        public int Id { get; set; }
        //public int ModuleId { get; set; }
        //public string ModuleTitle { get; set; }
        //public int ModuleResult { get; set; }
        //public string ModuleTrimester { get; set; }
        //public string ModuleComment { get; set; }
        [Display(Name = "Module ID")]
        [Range(100000, 999999, ErrorMessage = "Module ID must be 6-digits long.")]
        [Required(ErrorMessage = "Please enter a valid Module ID.")]
        public int ModuleId { get; set; }

        [Display(Name = "Module Title")]
        [Required(ErrorMessage = "Please enter a valid Module Title.")]
        public string ModuleTitle { get; set; }

        [Display(Name = "Module Result")]
        [Range(000, 100, ErrorMessage = "Module Result must be no longer than 3-digits.\n and range from 0 to  100.")]
        [Required(ErrorMessage = "Please enter a valid Module Result.")]
        public int ModuleResult { get; set; }

        [Display(Name = "Module Trimester")]
        [Required(ErrorMessage = "Please enter a valid Module Trimester.")]
        public string ModuleTrimester { get; set; }

        [Display(Name = "Module Comment")]
        [Required(ErrorMessage = "Please enter a valid Module Comment.")]
        public string ModuleComment { get; set; }
    }
}
