//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Transcript_Repository.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Module
    {
        public int Id { get; set; }
        public int ModuleId { get; set; }
        public string ModuleTitle { get; set; }
        public int ModuleResult { get; set; }
        public string ModuleTrimester { get; set; }
        public string ModuleComment { get; set; }
    }
}
