//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Transcript_Repository.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transcript
    {
        public int Id { get; set; }
        public int TranscriptId { get; set; }
        public System.DateTime TranscriptDate { get; set; }
        public bool TranscriptStatus { get; set; }
    }
}
